### PR TITLE
Fix transaction extensions to handle failures correctly

### LINKED ISSUE #23: Transaction does not return the expected Failure
Hey :wave: ,

please checkout this spec. I expect that the code rolls back and returns the `Failure(:failure)`, but instead it returns `Success(nil)`. 
Am i misunderstanding something, or is this wrong behavior? If yes, what's the correct way to return the `Failure`.

```ruby
require "spec_helper"
require "dry/operation"

RSpec.describe Dry::Operation::Extensions::ROM do
  include Dry::Monads[:result]

  let(:rom) do
    ROM.container(:sql, "sqlite:memory") do |config|
      config.default.create_table(:foo) do
        column :bar, :string
      end

      config.relation(:foo)
    end
  end

  let(:base) do
    Class.new(Dry::Operation) do
      include Dry::Operation::Extensions::ROM

      attr_reader :rom

      def initialize(rom:)
        @rom = rom
        super()
      end
    end
  end

  it "should roll back and return the failure" do
    instance = Class.new(base) do
      def call
        transaction do
          step create_record
          step failure
        end
      end

      def create_record
        Success(rom.relations[:foo].command(:create).call(bar: "bar"))
      end

      def failure
        Failure(:failure)
      end
    end.new(rom: rom)

    result = instance.call

    expect(result).to be_failure
  end
end
```
Thanks!

### PR DESCRIPTION
**Pull request by waiting-for-dev**
## Overview

The `intercepting_failure` method was not handling the block's output correctly when it was a failure. It wasn't throwing `:halt` with the failure as the given handlers were raising and therefore the throwing part was never reached.

We modify the method to pass the failure to the handler and skip the throwing part, while extensions need to work in two phases:

1 - From within the transaction block, they intercept a failure a first time and assign it to a `result` variable available from the outer scope. After that, they raise to rollback the transaction but return the `result` variable after that.

2 - From outside the transaction block, they throw again the failure when the `result` is actually a failure.

We also make public the `throw_failure` method so that other extensions can create similar behavior.

We also add a warning in the ActiveRecord extension to make it clear that the `:requires_new` option is not yet supported for this approach. We should find a way to make it work in the future.

Closes #23

### CODE REVIEW

File: lib/dry/operation/extensions/active_record.rb [hunk 1]
```diff
@@ -109,8 +111,17 @@ def included(klass)
               #   @see Dry::Operation#steps
               #   @see https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/DatabaseStatements.html#method-i-transaction
               klass.define_method(:transaction) do |connection = default_connection, **opts, &steps|
-                connection.transaction(**options.merge(opts)) do
-                  intercepting_failure(-> { raise ::ActiveRecord::Rollback }, &steps)
+                intercepting_failure(method(:throw_failure)) do
```
Comment (timriley) [inline lib/dry/operation/extensions/active_record.rb:114]: Looking at the two extensions we're changing here, we're passing `method(:throw_failure)` as the first argument in both cases.

Would you expect this `throw_failure` method to be used like this in all extensions?

If so, I wonder if we could make it the default. I toyed with changing the `#intercepting_failure` params to:

```ruby
def intercepting_failure(handler = method(:throw_failure), &block)
```

And then updating these extensions, so all they do is `intercepting_failure do`.

With these, the tests all still pass. What do you think?

**Review by timriley — APPROVED** [review]
@waiting-for-dev Changes look good.

It seems like the job of writing an extension has become a bit more complicated with this change, but if that's what's necessary to provide correct behaviour, then that's fine :) The extensions still seem straightforward enough to follow.

I've left one suggestion about how we can simplify things a little. Happy for you to decide what you think is best for that.

File: lib/dry/operation/extensions/active_record.rb (hunk 1 above)
Comment (waiting-for-dev) [reply lib/dry/operation/extensions/active_record.rb]: That's a great suggestion. A smart change to make it look much cleaner. Done!

**Comment by waiting-for-dev** [comment]
> It seems like the job of writing an extension has become a bit more complicated with this change, but if that's what's necessary to provide correct behaviour, then that's fine :)

Yeah, unfortunately now everything becomes more cumbersome, but unfortunately I can't see any other way to workaround the two mechanisms breaking the control flow in sequence :/
